version: "3"


services:
  hpasmcli-exporter:
#    build:
#      dockerfile: Dockerfile
#      context: .
    image: php:8.1-apache
    container_name: hp_exporter
    hostname: hp_exporter

    volumes:
      - /var/hpasmcli:/hpasmcli:ro
      - "./src:/var/www/html:z"

networks:
  default:
    external:
      name: proxynet
